Force checkout submodules
Between two builds I got, repeatedly:

    $ git submodule sync --recursive
    Synchronizing submodule url for 'submodule'
    $ git submodule update --init --recursive
    error: Your local changes to the following files would be overwritten by checkout:
        command
    Please commit your changes or stash them before you can switch branches.
    Aborting
    Unable to checkout '78f4fa2685f43c33771d702b3bbc5f7e238d1dc9' in submodule path 'submodule'

It seems the git clean wasn't enough and this required a force, which
fixed the issue on a subsequent run.