fix: dedup arguments to git when fetching submodule
For a git repository that uses submodules, the agent
currently appends the same arguments per submodule to
the git command line, which is less than ideal and results
in the following error (for 2 submodules):

```
$ git submodule update --init --recursive --force submodule update --init --recursive --force
error: pathspec 'submodule' did not match any file(s) known to git
error: pathspec 'update' did not match any file(s) known to git
error: pathspec '--init' did not match any file(s) known to git
error: pathspec '--recursive' did not match any file(s) known to git
error: pathspec '--force' did not match any file(s) known to git
```

The goal of this commit is to ensure the arguments
are reinitialized per submodule in order to prevent this
situation.